### ISSUE TITLE
Starting Points

### ISSUE THREAD

**Issue by changkun** [changkun/midgard#1]
Initial needs from @changkun 

- [x] sync clipboard between devices (iOS+macOS+Linux)
- [x] code2img, code and images

Initial needs from @qcrao:

- [x] 一键上传剪贴板里的图片到云主机，返回自定域名的 md 格式的图片链接
- [x] ~~自动调整大小使得整体看起来比较一致（有时我画了一张局部的图，贴上去看起来放的很大）~~ 原因不明，建议自行导出结果再进行上传: `mg alloc`
- [x] 定时加密/解密上传到 github

Initial needs from @yangwenmai 

- [x] searchable code2img history

## TODO

- [x] installation script for daemon process
- [x] authenticated gRPC calls: no need because rpc are served from local
- [x] basic auth with maximum failure control
- [x] websocket clipboard push registration/notification
- [x] iOS shortcut for clipboard data fetching
- [x] config initialization, both for client and server (can we use init for daemon/server installation?)
- [x] code2img
- [x] VCS backup
- [x] register keyboard hotkey
- [x] clipboard history
- [x] list all daemons
- [x] code2img can select lines
- [x] code2img timeline
- [x] backup from container
- [ ] integrate telegram

**Comment by changkun** [comment]
I don't think the support of telegram is necessary, it basically conflicts with the idea of Midgard CLI. Close because most of the major features are implemented.
